export const sliderItems = [
    {
        id: 1,
        img: "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/a4d975e141054d24a0eaaae700d36352_9366/SUPERSTAR_SHOES_White_EG4960_01_standard.jpg",
        title: "SUMMER SALE",
        desc: "DON'T COMPROMISE ON STYLE! GET 30% OFF FOR NEW ARRIVALS.",
        bg: "f5fafd",
    },
    {
        id: 2,
        img: "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/a0f832b935524a2bad4bada8003f0bdf_9366/SUPERSTAR_SHOES_White_GZ3741_01_standard.jpg",
        title: "VALENTINE SALE",
        desc: "LET YOUR HEART LEAD THE WAY IN OUR VALENTINE DAY COLLECTION.",
        bg: "f5fafd",
    },
    {
        id: 3,
        img: "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/a83a298f23f047588233af9c009f63cd_9366/Adilette_Ayoon_Slides_Green_FZ6411_01_standard.jpg",
        title: "WEEKEND SPECIAL",
        desc: "JUST DO IT. LET GET 25% OFF FOR NEW SLIDES SHOES IN WEEKEND.",
        bg: "f5fafd",
    },
];

export const categories = [
    {
        id: 1,
        img: "https://i.pinimg.com/originals/af/db/fa/afdbfa42ec1fbb2c54ebef5f0fdacf1b.jpg",
        title: "MAN",
    },
    {
        id: 2,
        img: "https://i.pinimg.com/736x/6b/b3/3f/6bb33f130b68ab06e2398a37e4d997b4.jpg",
        title: "WOMAN",
    },
    {
        id: 3,
        img: "https://cdn.shopify.com/s/files/1/0627/5740/4909/files/section-05-how-to-style-mesh.shoes.jpg?v=1660187431&width=500",
        title: "SPORT",
    },
];

export const popularProducts = [
    {
        id: 1,
        img: "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/a4d975e141054d24a0eaaae700d36352_9366/SUPERSTAR_SHOES_White_EG4960_01_standard.jpg",
        name: "SUPERSTAR SHOES | WOMAN",
        desc: "Originally made for basketball courts in the '70s. Celebrated by hip hop royalty in the '80s. The adidas Superstar shoe is now a lifestyle staple for streetwear enthusiasts. The world-famous shell toe feature remains, providing style and protection. Just like it did on the B-ball courts back in the day. Now, whether at a festival or walking in the street you can enjoy yourself without the fear of being stepped on. The serrated 3-Stripes detail and adidas Superstar box logo adds OG authenticity to your look.",
        cat: "W",
        color: "white",
        price: 135,
    },
    {
        id: 2,
        img: "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/edba3c7374004e8891eeaf8900a49bde_9366/Adilette_Essential_Slides_Pink_HQ2055_01_standard.jpg",
        name: "ADILETTE ESSENTIAL SLIDES | WOMAN",
        desc: "Puffed-up perfection. With a wide upper designed in three puffy stripes, these laid-back adidas slides go all out on comfort. The padded footbed hugs your feet as you walk, and smooth synthetic leather looks seriously sleek. A Trefoil logo along each side makes a subtle appearance in tonal hues, and a synthetic outsole keeps a good grip on every step.",
        cat: "W",
        color: "pink",
        price: 65,
    },
    {
        id: 3,
        img: "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/eccd00cf1df64b4eb36baf460161037d_9366/Adifom_Adilette_Slides_Black_HQ7218_01_standard.jpg",
        name: "ADIFOM ADILETTE SLIDES | MAN",
        desc: "These adidas slides are ready to take you into the metaverse. A one-piece sugar cane foam construction creates a unique design, and the iconic Adilette silhouette ensures you'll be comfortable whether you're exploring virtual reality or just kicking back poolside. These slides are disrupting and redefining what it means to use fashion for good.These slides are made with natural and renewable materials as part of our journey to design out finite resources and help end plastic waste.",
        cat: "M",
        color: "black",
        price: 50,
    },
    {
        id: 4,
        img: "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/443492f89d124c8aa997af89012bfdb7_9366/Ultraboost_Light_Shoes_White_GY9350_01_standard.jpg",
        name: "ULTRABOOST LIGHT SHOES | WOMAN",
        desc: "Experience epic energy with the new Ultraboost Light, our lightest Ultraboost ever. The magic lies in the Light BOOST midsole, a new generation of adidas BOOST. Its unique molecule design achieves the lightest BOOST foam to date. With hundreds of BOOST capsules bursting with energy and ultimate cushioning and comfort, some feet really can have it all.",
        cat: "S",
        color: "white",
        price: 230,
    },
];

export const products = [
    {
        id: 1,
        img: "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/eccd00cf1df64b4eb36baf460161037d_9366/Adifom_Adilette_Slides_Black_HQ7218_01_standard.jpg",
        name: "ADIFOM ADILETTE SLIDES | MAN",
        desc: "These adidas slides are ready to take you into the metaverse. A one-piece sugar cane foam construction creates a unique design, and the iconic Adilette silhouette ensures you'll be comfortable whether you're exploring virtual reality or just kicking back poolside. These slides are disrupting and redefining what it means to use fashion for good.These slides are made with natural and renewable materials as part of our journey to design out finite resources and help end plastic waste.",
        cat: "M",
        color: "black",
        price: 50,
    },
    {
        id: 2,
        img: "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/a4d975e141054d24a0eaaae700d36352_9366/SUPERSTAR_SHOES_White_EG4960_01_standard.jpg",
        name: "SUPERSTAR SHOES | WOMAN",
        desc: "Originally made for basketball courts in the '70s. Celebrated by hip hop royalty in the '80s. The adidas Superstar shoe is now a lifestyle staple for streetwear enthusiasts. The world-famous shell toe feature remains, providing style and protection. Just like it did on the B-ball courts back in the day. Now, whether at a festival or walking in the street you can enjoy yourself without the fear of being stepped on. The serrated 3-Stripes detail and adidas Superstar box logo adds OG authenticity to your look.",
        cat: "W",
        color: "white",
        price: 135,
    },
    {
        id: 3,
        img: "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/443492f89d124c8aa997af89012bfdb7_9366/Ultraboost_Light_Shoes_White_GY9350_01_standard.jpg",
        name: "ULTRABOOST LIGHT SHOES | WOMAN",
        desc: "Experience epic energy with the new Ultraboost Light, our lightest Ultraboost ever. The magic lies in the Light BOOST midsole, a new generation of adidas BOOST. Its unique molecule design achieves the lightest BOOST foam to date. With hundreds of BOOST capsules bursting with energy and ultimate cushioning and comfort, some feet really can have it all.",
        cat: "S",
        color: "white",
        price: 230,
    },
    {
        id: 4,
        img: "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/757d62aebc704ced8cc2acaa0115efcb_9366/Terrex_Voyager_21_Travel_Shoes_Black_FZ2225_01_standard.jpg",
        name: "TERREX VOYAGER 21 TRAVEL SHOES | MAN",
        desc: "Pack light and be ready for anything. These travel shoes combine the rugged all-terrain outsole of a trail runner with a light, flexible design for efficient packing. The result is a go-anywhere sneaker with a soft breathable feel. Wear them with or without socks. Slip them on, pull the bungee lace and start exploring.",
        cat: "M",
        color: "black",
        price: 120,
    },
    {
        id: 5,
        img: "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/edba3c7374004e8891eeaf8900a49bde_9366/Adilette_Essential_Slides_Pink_HQ2055_01_standard.jpg",
        name: "ADILETTE ESSENTIAL SLIDES | WOMAN",
        desc: "Puffed-up perfection. With a wide upper designed in three puffy stripes, these laid-back adidas slides go all out on comfort. The padded footbed hugs your feet as you walk, and smooth synthetic leather looks seriously sleek. A Trefoil logo along each side makes a subtle appearance in tonal hues, and a synthetic outsole keeps a good grip on every step.",
        cat: "W",
        color: "pink",
        price: 65,
    },
    {
        id: 6,
        img: "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/f29cacd3c14945d59864ad2600aa3f54_9366/adidas_by_Stella_McCartney_Treino_Shoes_Beige_G57801_01_standard.jpg",
        name: "STELLA MCCARTNEY TREINO SHOES | WOMAN",
        desc: "If you're going to go for it, why limit yourself? These adidas by Stella McCartney training shoes are all about impact. So make the most of it when you lace into them, both on the weight floor and with your style. High-shine metallic details catch the light. The more energy you give, the more you get back with charged Boost cushioning. Go ahead and turn up the intensity — the TPU heel clip supports all your moves.",
        cat: "S",
        color: "#EAD4BA",
        price: 85,
    },
    {
        id: 7,
        img: "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/9bed56d5ccdd46aca708af2b000c6d0c_9366/Forum_Low_Shoes_White_GY0003_01_standard.jpg",
        name: "FORUM LOW SHOES | MAN",
        desc: "For nearly 40 years, the Forum has been a staple of the adidas lineup. This pair of the iconic shoes stays true to the original with signature 3-Stripes and the classic cross overlay. Colourblocking on the leather upper adds contrast for a versatile look that's both polished and intrepid.",
        cat: "M",
        color: "#B1C6DE",
        price: 125,
    },
    {
        id: 8,
        img: "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/882d1e01f08d423c848daaee01133764_9366/Adilette_Lite_Slides_Black_FU8298_01_standard.jpg",
        name: "ADILETTE LITE SLIDES | WOMAN",
        desc: "Full-time vacation vibes. These Adilette Lite Slides free your feet. (Or wear them with socks, no judgement here.) This pair features a super-soft footbed for an instantly comfy feel. There's an adidas Trefoil on top so you can feel sporty, even when you're lounging.",
        cat: "W",
        color: "black",
        price: 40,
    },
    {
        id: 9,
        img: "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/ec960dfe508c4aef8decaf89012e2e50_9366/Ultraboost_Light_Shoes_Orange_HQ6341_01_standard.jpg",
        name: "ULTRABOOST LIGHT SHOES | MAN",
        desc: "Experience epic energy with the new Ultraboost Light, our lightest Ultraboost ever. The magic lies in the Light BOOST midsole, a new generation of adidas BOOST. Its unique molecule design achieves the lightest BOOST foam to date. With hundreds of BOOST capsules bursting with energy and ultimate cushioning and comfort, some feet really can have it all.",
        cat: "S",
        color: "#FF4E3D",
        price: 235,
    },
    {
        id: 10,
        img: "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/a0f832b935524a2bad4bada8003f0bdf_9366/SUPERSTAR_SHOES_White_GZ3741_01_standard.jpg",
        name: "SUPERSTAR SHOES | MAN",
        desc: "Originally made for basketball courts in the '70s. Celebrated by hip hop royalty in the '80s. The adidas Superstar shoe is now a lifestyle staple for streetwear enthusiasts. The world-famous shell toe feature remains, providing style and protection. Just like it did on the B-ball courts back in the day. Now, whether at a festival or walking in the street you can enjoy yourself without the fear of being stepped on. The serrated 3-Stripes detail and adidas Superstar box logo adds OG authenticity to your look.",
        cat: "M",
        color: "red",
        price: 130,
    },
    {
        id: 11,
        img: "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/394853d9113341c4829faf9c011d9cd1_9366/Superstar_Shoes_White_HQ1906_01_standard.jpg",
        name: "SUPERSTAR SHOES | WOMAN",
        desc: "adidas Superstar shoes were made for the hardwood but soon adopted on the stage, the catwalk and everywhere in between. Since 1970 they've remained one of the world's most popular trainers, with the classic shell toe striding into the spotlight time and time again. This version's perforated 3-Stripes and rubber cupsole carry on the tradition, proving that an icon never fades, it only gets better with time.",
        cat: "W",
        color: "pink",
        price: 130,
    },
    {
        id: 12,
        img: "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/5358e9b99c1f41aabcc2af47009b38f7_9366/Ultrabounce_Shoes_Blue_HP5774_01_standard.jpg",
        name: "ULTRABOUNCE SHOES | MAN",
        desc: "Ready to ramp up your training? These adidas shoes help you take the next step in your running journey. Lightweight Bounce cushioning provides comfort and flexibility to keep you energised when you add kilometres to your daily run. The long-lasting rubber outsole ensures traction on varied surfaces so you can stride with confidence.",
        cat: "S",
        color: "#425074",
        price: 100,
    },
    {
        id: 13,
        img: "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/9e99f56e65f445f4a5f6af8d0082f890_9366/Adilette_22_Slides_Brown_HP6518_01_standard.jpg",
        name: "ADILETTE 22 SLIDES | MAN",
        desc: "For the design of these adidas slides we looked to topographic maps illustrating expeditions to Mars and the dimensional stages of a new planet. And the futuristic vibes don't end there. They're built with material made in part from sugarcane, one step on the road to a more sustainable future. Wear them on diverse terrain from wet to dry.",
        cat: "M",
        color: "#B48475",
        price: 70,
    },
    {
        id: 14,
        img: "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/a83a298f23f047588233af9c009f63cd_9366/Adilette_Ayoon_Slides_Green_FZ6411_01_standard.jpg",
        name: "ADILETTE AYOON SLIDES | WOMAN",
        desc: "Anything is possible when your comfort comes first. Taking cues from the wide open world of the metaverse, these adidas slides step a confident stride. The one-piece EVA design is soft and flexible, from the lining to the upper to the outsole. Embossed 3-Stripes on the upper add a signature touch, echoed by three Trefoils to sign off your look.",
        cat: "W",
        color: "lightgreen",
        price: 60,
    },
];